
on:
  push:
    branches:
      - main
env:
  GITURL: ${{ secrets.APP_SVC_GIT_URL }}
  MESSAGE: ${{ github.event.head_commit.message }}
  GITUSR: ${{ secrets.APP_SVC_GIT_USER }}
  GITPASS: ${{ secrets.APP_SVC_GIT_PASSWORD }}
  NODE_VERSION: '14.x'
  CI: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test --if-present
      run: |
        npm install
        npm run build --if-present
      
    - name: 'Deploy to Web'
      run: |
        git clone "$GITURL"
        cp -ra build/* NH4HApps/static/TeamBuilder
        cd NH4HAppss
        git add .
        git commit -m "$MESSAGE"
        git push